M48
; DRILL file KiCad 10.0.0 date 2026-08-16T09:25:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-16T09:25:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X60.634Y-96.17
X61.65Y-101.25
X62.666Y-96.17
T2
X52.75Y-21.4
X52.75Y-187.0
X61.95Y-21.4
X61.95Y-187.0
M30
